labels_to_predict:
  [
    "ROOM",
    "WINDOW",
    "DOOR",
    "STAIRCASE",
    "KITCHEN",
    "LIVING",
    "RESTROOM",
    "BEDROOM",
    "GARAGE",
    "OTHER",
  ]
room_model_name: "room_config_yolov8m"
window_door_model_name: "window_door_config_yolov8m_wd"
staircase_model_name: "staircase_config_yolov8m"
room_type_model_name: "room_type_config_yolov8m"
eval_data_file: "data/annotation/evaluation/Econest_test_set_floorplans_211123.csv"
hw_json_path: "data/annotation/prodigy_labelled/quality_dataset.jsonl"
prodigy_labelled_date:
  room_dataset: "211123"
  window_door_staircase_dataset: "211123"
  room_type_from_labels_dataset: "211123"
