path: "data/annotation/prodigy_labelled/301023/yolo_formatted/staircase_yolo_formatted/"
train: images/train
val: images/val
test: images/test
save_dir: "staircase_save_dir/"

nc: 1
names: ["STAIRCASE"]
