path: "data/annotation/prodigy_labelled/191023/window_door_staircase_yolo_formatted/"
train: images/train
val: images/val
test: images/test
save_dir: "window_door_save_dir/"

nc: 3
names: ["WINDOW", "DOOR", "STAIRCASE"]
