path: "data/annotation/prodigy_labelled/301023/yolo_formatted/window_door_prodigy_plus_roboflow/"
train: images/train
val: images/val
test: images/test
save_dir: "window_door_save_dir/"

nc: 2
names: ["WINDOW", "DOOR"]
